Repository skyra-project/tags, pull requests merged in 2020-10, with the labels that each got.

#3 feat: added Random
  src/index.ts
  src/lib/errors/ParserRandomDuplicatedOptionsError.ts
  src/lib/errors/ParserRandomMissingOptionsError.ts
  src/lib/parser/Parser.ts
  src/lib/structures/Random.ts
  src/lib/structures/Tag.ts
  tests/parser/Parser.test.ts
  tests/structures/Random.test.ts
Labels: Meta: Feature, SEM: Minor, Status: Review Ready, Type: Enhancement

#4 fix(lgtm): resolve LGTM warnings
  src/lib/parser/Parser.ts
Labels: Meta: BugFix, SEM: Patch, Type: Maintenance

#5 docs(readme): fix depfu badge
  README.md
Labels: Event: Hacktoberfest, Meta: Github

#6 test: added more tests to increase coverage
  tests/parser/Parser.test.ts
Labels: Event: Hacktoberfest, Meta: Error Handling, SEM: Patch, Status: Review Ready

#7 refactor: added messages to all errors
  src/lib/errors/ParserEmptyStringTagError.ts
  src/lib/errors/ParserMissingTokenError.ts
  src/lib/errors/ParserPickMissingOptionsError.ts
  src/lib/errors/ParserRandomDuplicatedOptionsError.ts
  src/lib/errors/ParserRandomMissingOptionsError.ts
  src/lib/errors/ParserUnexpectedTokenError.ts
  src/lib/errors/SentenceMissingArgumentError.ts
  src/lib/errors/TransformerInvalidFormatterError.ts
  src/lib/structures/Transformer.ts
Labels: Event: Hacktoberfest, Meta: Error Handling, SEM: Patch, Status: Review Ready, Type: Enhancement
