Repository skyra-project/tags, pull requests merged in 2021-02, with the labels that each got.

#26 refactor: added a few QoL features
  jest.config.js
  src/index.ts
  src/lib/errors/MismatchingNamedArgumentTypeValidationError.ts
  src/lib/errors/ParserUnexpectedTokenError.ts
  src/lib/errors/PickInvalidOptionError.ts
  src/lib/errors/TransformerInvalidFormatterError.ts
  src/lib/errors/Unreachable.ts
  src/lib/parser/Parser.ts
  src/lib/structures/ISentencePart.ts
  src/lib/structures/Pick.ts
  src/lib/structures/Random.ts
  src/lib/structures/Sentence.ts
  src/lib/structures/Tag.ts
  src/lib/structures/Transformer.ts
  tests/parser/Parser.test.ts
  tests/structures/Pick.test.ts
  tests/structures/Random.test.ts
  tests/structures/Sentence.test.ts
  tests/structures/Tag.test.ts
  tests/structures/Transformer.test.ts
Labels: Meta: Feature, Meta: Refactor

#27 fix: resolved circular
  src/index.ts
  src/lib/structures/Sentence.ts
  src/lib/util/util.ts
  tests/structures/Sentence.test.ts
  tests/util/util.test.ts
Labels: Meta: BugFix

#28 fix: remove rollup
  package.json
  rollup.config.ts
  tests/tsconfig.json
  tsconfig.base.json
  tsconfig.eslint.json
  yarn.lock
Labels: Meta: BugFix, Meta: Refactor, Priority: High, SEM: Patch

#30 feat(errors): added identifier property
  src/index.ts
  src/lib/errors/MismatchingNamedArgumentTypeValidationError.ts
  src/lib/errors/ParserEmptyStringTagError.ts
  src/lib/errors/ParserMissingTokenError.ts
  src/lib/errors/ParserPickMissingOptionsError.ts
  src/lib/errors/ParserRandomDuplicatedOptionsError.ts
  src/lib/errors/ParserRandomMissingOptionsError.ts
  src/lib/errors/ParserUnexpectedTokenError.ts
  src/lib/errors/PickInvalidOptionError.ts
  src/lib/errors/SentenceMissingArgumentError.ts
  src/lib/errors/TransformerInvalidFormatterError.ts
  src/lib/errors/base/UserError.ts
  src/lib/structures/Pick.ts
Labels: Meta: Feature

#31 fix: make identifiers camelCase
  src/lib/errors/base/UserError.ts
Labels: Meta: BugFix, Priority: High
